spring:

  mvc:
    static-path-pattern: /static/**


  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://database-2.cydbsa2db7fu.ap-south-1.rds.amazonaws.com/postgres
    username: postgres
    password: 12345678

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
      format_sql: true

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: false

server:
  port: 8082
